name: .NET Core CI

on:
  push:
    branches: [ chrome-issue ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Chrome and ChromeDriver
      run: |
        $Path = $env:TEMP; $Installer = "chromesetup.exe"; Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chromesetup.exe" -OutFile $Path\$Installer; Start-Process -FilePath "$Path\$Installer" -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path\$Installer
        $driverVersion = (Invoke-WebRequest -Uri https://chromedriver.storage.googleapis.com/LATEST_RELEASE).Content.Trim();
        $driverUrl = "https://chromedriver.storage.googleapis.com/$driverVersion/chromedriver_win32.zip";
        Invoke-WebRequest -Uri $driverUrl -OutFile "chromedriver.zip";
        Expand-Archive -Path "chromedriver.zip" -DestinationPath "C:\tools\";
        Add-MpPreference -ExclusionPath "C:\tools\";
      shell: powershell

    - name: Display Chrome and ChromeDriver version
      run: |
        google-chrome --version
        chromedriver --version
      shell: powershell

