name: .NET Core CI

on:
  push:
    branches: [ chrome-issue ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Chrome
      run: |
        sudo apt-get install -y libxss1  libappindicator1 libindicator7
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome*.deb
        sudo apt-get install -f
        google-chrome --version
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
        chromedriver --version

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101' # adjust this to your project's .NET version

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run Selenium Tests
      run: dotnet test --filter FullyQualifiedName~YourNamespace.YourTestClassName # replace with your test class name
