name: Your Workflow Name

on:
  push:
    branches:
      - core-pack  # Modify this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install node-fetch for Corepack
        run: pnpm install node-fetch || npm install node-fetch

      - name: Setup globalThis.fetch for Corepack
        run: echo "globalThis.fetch = require('node-fetch');" >> $GITHUB_ENV

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
