name: Build Only (Android)

on:
  push:

jobs:
  build-only-android:
    name: Build only (Android)
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
   

      # Step 4: Perform .NET workload search
      - name: Run .NET Workload Search
        run: dotnet workload search
