name: Show enable
on: push
jobs:
  show:
    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-22.04, ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1
    steps:
      - run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            systemctl --user enable --now podman.socket
          fi
          podman system info
