name: Check zstd Version

on: [push]

jobs:
  check-zstd-version:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install zstd
        run: sudo apt-get update && sudo apt-get install -y zstd

      - name: Check zstd Version
        run: zstd -V
